### ISSUE TITLE
Installation via pip, Ubuntu 20.04

### ISSUE THREAD

**Issue by jodavies** [gudrunhe/secdec#13]
Hello,

Probably I have just not set up my environment properly, but I am having issues running, eg, the box1L example after installation with pip according to https://secdec.readthedocs.io/en/stable/installation.html .

I can run `generate_box1L.py` and then `make -C box1L` without error, but when I then run `integrate_box1L.py` I have the following:
```
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat                                                                                                        
Traceback (most recent call last):                                                                                                                                              
  File "./integrate_box1L.py", line 8, in <module>                                                                                                                              
    box1L = IntegralLibrary('box1L/box1L_pylink.so')                                                                                                                            
  File "/home/josh/.local/lib/python3.8/site-packages/pySecDec/integral_interface.py", line 1014, in __init__                                                                   
    c_lib = self.c_lib = CDLL(shared_object_path)                                                                                                                               
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__                                                                                                           
    self._handle = _dlopen(self._name, mode)                                                                                                                                    
OSError: box1L/box1L_pylink.so: undefined symbol: _ZN5GiNaC18get_default_readerB5cxx11Ev                                                                                        
```

libginac is available, supposedly:
```
$ ldconfig -p | grep ginac

libginac.so.6 (libc6,x86-64) => /lib/libginac.so.6
libginac.so (libc6,x86-64) => /lib/libginac.so    
```

Am I doing something wrong, here?

Thanks,
Josh.

**Comment by magv** [comment]
Hi, Josh & Vlad. Could you re-check this with pySecDec v1.6? We no longer link with ginac, so it should be better in that regard. But then, something else might be broken, we just want to know what :)

**Comment by jodavies** [comment]
Hi Vitaly. Now installation with pip on 20.04 (and 22.04) goes smoothly, and I can run the box1L example.

**Comment by vsht** [comment]
Same here, everything seems to work fine with Fedora 37.

As far as the TTP machines are concerned, they still only have Python 3.6, 
so there one is stuck with pySecDec 1.5.6. I guess we will have to wait for the admins to upgrade 
to openSUSE Leap 15.5: it should be released in the next few days.

**Comment by magv** [comment]
Thanks for checking fast. I'm glad it works, we've spent a lot of effort on this trivial problem.

Vlad, TTP machines have `python3.10`, that's what we're using.

**Comment by vsht** [comment]
@magv You are right, I was always using `python3` which calls python 3.6, but indeed one can also run `python3.10` :)
