### ISSUE TITLE
Weird problem in the make process

### ISSUE THREAD

**Issue by gkdgoutam** [gudrunhe/secdec#25]
Hi, 

I have experienced a weird problem while doing the making process with 1.5.3 for one of my sectors. The problem probably comes from FORM but I could be wrong. The weird part is, that I can not reproduce the problem every time I run (it appears rarely). So I am not sure if this is a problem or not and I just wanted to bring this log message to the experts if they know of this issue.

python3: 3.7.3
pysecdec: 1.5.3
form: 4.2.1
sympy: 1.9
mpmath: 1.2.1

The log is the following:

TFORM 4.2.1 (Nov 21 2018, v4.2.1) 64-bits 8 workers  Run: Tue Jun 14 21:10:29 2022
    #-
Cannot take gcd
Cannot take gcd
Division by zero
Cannot take gcd
Cannot take gcd
Division by zero
Cannot take gcd
Cannot take gcd
Division by zero
Division by zero
Division by zero
Cannot take gcd
Cannot take gcd
Division by zero
Cannot take gcd
Cannot take gcd
Division by zero
Division by zero
Division by zero
Cannot take gcd
Cannot take gcd
Division by zero
Cannot take gcd
Cannot take gcd
Division by zero
Division by zero
Division by zero
Cannot take gcd
Cannot take gcd
Division by zero
Cannot take gcd
Cannot take gcd
Division by zero
Division by zero
Division by zero
Cannot take gcd
Cannot take gcd

and it hangs there indefinitely. If I kill the process and rerun it runs fine and integrates after that and returns correct results. 
Is it a familiar problem (if it is a problem at all)? 

Best, 
GD

**Comment by gkdgoutam** [comment]
In the same case, a different type of error appears while re-making:

`g++ -c -O2 -std=c++14 -I. -I/scratch/test/sector_test/sector_test_integral/codegen/ -I"/home/users/gd/.local/lib/python3.7/site-packages/pySecDecContrib/include" -fPIC src/prefactor.cpp -o src/prefactor.o
TFORM 4.2.1 (Nov 21 2018, v4.2.1) 64-bits 8 workers  Run: Tue Jun 14 23:06:56 2022
    #-
Unexpected code in ReNumber
Program terminating in thread 7 at write_integrand.frm Line 521 -->
  7.58 sec + 78.16 sec: 85.74 sec out of 39.50 sec
make[1]: *** [Makefile:41: codegen/sector1.done] Error 1
make[1]: Leaving directory '/scratch/gd/test/sector_test/sector_test_integral'
make: *** [Makefile:17: sector_test_integral/libsector_test_integral.a] Error 2
make: Leaving directory '/scratch/gd/test/sector_test'`



Changing form threads does fix it  `form_threads=15,` :



`g++ -c -O2 -std=c++14 -I. -I/scratch/gd/test/sector_test_integral/codegen/ -I"/home/users/gd/.local/lib/python3.7/site-packages/pySecDecContrib/include" -fPIC src/prefactor.cpp -o src/prefactor.o
TFORM 4.2.1 (Nov 21 2018, v4.2.1) 64-bits 15 workers  Run: Tue Jun 14 23:20:50 2022
    #-
  40.84 sec + 495.06 sec: 535.91 sec out of 91.55 sec
python3 codegen/export_sector codegen/sector1.info src/
* Creating src/sector_1.cpp
* Creating src/sector_1_n1_n4.cpp
* Creating src/sector_1_n1_n4.hpp`

Looks like something is broken in `write_integrand.frm`!

**Comment by spj101** [comment]
Hi @gkdgoutam,

The errors you are reporting all come from FORM (likely `write_integrand.frm`). This is either a bug in our FORM code or within FORM itself.

Could you please provide a minimal working example that produces this bug or, failing that, the pySecDec example that generated the bug?

**Comment by spj101** [comment]
Hi @gkdgoutam, we have identified a few new cases where FORM bugs cause issues within pySecDec. Some of these bugs have been fixed in the latest version of FORM.

Could I suggest you try the following:
- obtain FORM from their [git page](https://github.com/vermaseren/form)
- build the binaries from source following their instructions
- replace the `form` and `tform` binaries in your `pySecDecContrib/bin` with these binaries and confirm that pySecDec is finding your new binaries from the output

It would be useful for us if you can confirm if this fixes these bugs or not (then we know whether or not to close this issue once we ship a later FORM version).

**Comment by gkdgoutam** [comment]
Hi @spj101, this problem was so random that I could not reproduce it a second time with the same settings (I don't know why). This is why I can not make a minimal example for this. I will report if I face the issue again, and we can close the issue for the time being.
