### ISSUE TITLE
Mathematica/Maple export?

### ISSUE THREAD

**Issue by vsht** [gudrunhe/secdec#3]
One thing I was wondering about, is whether there is a convenient way to export
the numerical results (and possibly also symbolical expressions for Feynman parameter integrals)
to Mathematica or Maple?

This would be particularly useful when cross-checking analytic results obtained with PolyLogTools/HPL (Mathematica)
or HyperInt (Maple) against the output of pySecDec.

**Comment by magv** [comment]
It crossed my mind that being silent on this issue tracker for so long might make it look like we don't even read it... while in fact the opposite it true.

Sorry for being silent; we *will* add `convert_to_{mathematica,maple,ginac,sympy}` functions in the new release, whenever it happens. Hopefully this will cover all the relevant use cases.

**Comment by magv** [comment]
In the new release one can transform the numerical integration result into Mathematica format with [series_to_mathematica](https://secdec.readthedocs.io/en/stable/full_reference.html#pySecDec.integral_interface.series_to_mathematica), and to Maple, GiNaC and SymPy with related functions. There's an example of using `series_to_sympy` in e.g. the [bubble1L_ebr](/gudrunhe/secdec/blob/v1.5.2/examples/bubble1L_ebr/integrate_bubble1L_ebr_large_mass.py) example (also in the [paper](https://arxiv.org/pdf/2108.10807.pdf)).

Comments on the API are welcome, but I'll close this issue for the moment.
