### ISSUE TITLE
GitHub Discussions as a forum for pySecDec?

### ISSUE THREAD

**Issue by vsht** [gudrunhe/secdec#8]
Now that GitHub Discussions is available for all repositories

https://github.blog/2021-08-17-github-discussions-out-of-beta/

I'm wondering if it would be a good idea to enable it here and use it as a forum for pySecDec users.

My personal experiences with Discussions in the FeynCalc repository 

https://github.com/FeynCalc/feyncalc/discussions

were mostly positive.

**Comment by spj101** [comment]
Thank you for this suggestion, we will enable the new GitHub Discussions feature too. Let's see if it is useful.
